### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by caprenter** [CooperativeIT/website#34]
make sure 404 page works

**Comment by Plebster** [comment]
bit beyond the scope of this piece of worker and should be more a server setting,,, 

keep as place holder

**Comment by caprenter** [comment]
FYI in GitHub pages you basically create a 404.html or 404.md page and it does the rest: https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site

**Comment by Plebster** [comment]
yep, that's a fairly common thing to do... I thought our intentions were no to have it on GitHub Pages

**Comment by caprenter** [comment]
Yup. Just leaving a note.
